version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get -y install nodejs && apt-get install -y npm && sudo apt-get install -y default-jdk && sudo apt-get -y install maven    
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - sh ./scripts/build-container.sh      
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
      - docker images
      - echo Pushing the Docker image...
      - docker push $ECR_REPO:latest
      docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG 